### ISSUE TITLE
Minor error during reboot ESP32-S3-N16R8

### ISSUE THREAD

**Issue by brightproject** [sivar2311/platformio_boards#2]
`Platformio.ini` settings
```
[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
monitor_port = COM6
upload_speed = 921600
upload_port = COM22
monitor_filters = esp32_exception_decoder
```
![esp32_s3_n16_r8](https://github.com/user-attachments/assets/99fb6926-6f43-411b-9f61-02a92ac0764a)

compilation and loading, this is the output

> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1-n16r8v.html
> PLATFORM: Espressif 32 (6.3.2) > Espressif ESP32-S3-DevKitC-1-N16R8V (16 MB QD, 8MB PSRAM)
> HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
> DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> PACKAGES:
>  - framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
>  - tool-esptoolpy @ 1.40501.0 (4.5.1)
>  - tool-mkfatfs @ 2.0.1
>  - tool-mklittlefs @ 1.203.210628 (2.3)
>  - tool-mkspiffs @ 2.230.0 (2.30)
>  - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
>  - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 34 compatible libraries

> Leaving...
> Hard resetting via RTS pin...
> =========================== [SUCCESS] Took 9.86 seconds =============================
>  Terminal will be reused by tasks, press any key to close it. 

I use this file

> https://github.com/sivar2311/platformio_boards/blob/main/boards/esp32-s3-devkitc1-n16r8.json

When rebooting I get this output in the serial monitor

> --- Terminal on COM6 | 115200 8-N-1
> --- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
> --- More details at https://bit.ly/pio-monitor-filters
> --- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
> SPIWP:0xee
> mode:DIO, clock div:1
> load:0x3fce3808,len:0x44c
> load:0x403c9700,len:0xbe4
> load:0x403cc700,len:0x2a38
> entry 0x403c98d4
> E (95) esp_core_dump_flash: Incorrect size of core dump image: 1174438437

Maybe you @sivar2311  can tell me what this is? I would be grateful.

**Comment by sivar2311** [comment]
> `framework-arduinoespressif32 @ 3.20009.0 (2.0.9)`

First you should update your platformio version.
Arduino core 2.0.9 is an ancient version.

Also try erase flash please and report back.

**Comment by sivar2311** [comment]
> `board = esp32-s3-devkitc-1-n16r8v`

Ermm... that's not the file I provide in this repo!

**Comment by brightproject** [comment]
> > `framework-arduinoespressif32 @ 3.20009.0 (2.0.9)`
> 
> First you should update your platformio version. Arduino core 2.0.9 is an ancient version.

This is the latest version, I think)
> https://registry.platformio.org/tools/platformio/framework-arduinoespressif32

```
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc1-n16r8.html
> PLATFORM: Espressif 32 (6.3.2) > Espressif ESP32-S3-DevKitC-1-N16R8V (16 MB Flash Quad, 8 MB PSRAM Octal)
> HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
> DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> PACKAGES:
>  - framework-arduinoespressif32 @ 3.20017.0 (2.0.17)
>  - tool-esptoolpy @ 1.40501.0 (4.5.1)
>  - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
>  - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 34 compatible libraries
```
The latest version is not very old, but I updated it on your advice.
Actually, you are right, I had two different files
Added a file with the name to the settings
After flashing, I got a cyclic reboot with multiple information output to the port monitor, regarding the new espressif kernel.
Returned it to how it was

> platform = espressif32
> ; platform_packages = platformio/framework-arduinoespressif32@^3.20017.0 

The version has become 

> framework-arduinoespressif32 @ 3.20009.0 (2.0.9) 

With your file it complains about the core ... 
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
E (104) esp_core_dump_flash: Core dump data check failed:
Calculated checksum='6a7cd56d'
Image checksum='ffffffff'
```

**Comment by sivar2311** [comment]
Please show your `platformio.ini`.
Otherwise the only thing I can do for you is guessing :/

**Comment by brightproject** [comment]
> Please show your `platformio.ini`. Otherwise the only thing I can do for you is guessing :/

```
[env:esp32-s3-devkitc1-n16r8]
platform = espressif32
; platform_packages = platformio/framework-arduinoespressif32@^3.20017.0
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
monitor_port = COM6
upload_speed = 921600
upload_port = COM22
monitor_filters = esp32_exception_decoder

lib_deps = bodmer/TFT_eSPI@^2.5.43
```

**Comment by sivar2311** [comment]
Try a simple clean project first:

`platformio.ini`
```
[env:esp32-s3-devkitc1-n16r8]
platform = espressif32 @ 6.8.1
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
```

`main.cpp`
```
#include <Arduino.h>

void setup() {
    Serial.begin(115200);
    Serial.println("Hello World");
}

void loop() {}
```

**Comment by sivar2311** [comment]
Why is your upload port different to the monitor port???

**Comment by brightproject** [comment]
> Try a simple clean project first:
> 
> `platformio.ini`
> 
> ```
> [env:esp32-s3-devkitc1-n16r8]
> platform = espressif32 @ 6.8.1
> board = esp32-s3-devkitc1-n16r8
> framework = arduino
> monitor_speed = 115200
> ```
> 
> `main.cpp`
> 
> ```
> #include <Arduino.h>
> 
> void setup() {
>     Serial.begin(115200);
>     Serial.println("Hello World");
> }
> 
> void loop() {}
> ```
My project is quite complex, it is drawing graphics on the display using the library `TFT_eSPI`.
Simple things like `BLINK` work.
I output such projects

> https://wokwi.com/projects/375745332267555841

or

> https://wokwi.com/projects/374062283976666113

The code simulator is slow, that's why the graphics are so slow🙂
There is no graphics output with the latest version of expressif.
That's why I stay on

> framework-arduinoespressif32 @ 3.20009.0 (2.0.9)

To get rid of the error in the port monitor
```
E (104) esp_core_dump_flash: Core dump data check failed:
Calculated checksum='6a7cd56d'
Image checksum='ffffffff'
```
Removed two lines related to the core.

    "extra_flags": [
      "-DARDUINO_ESP32S3_DEV",
      "-DARDUINO_RUNNING_CORE=1",
      "-DARDUINO_EVENT_RUNNING_CORE=1",
      "-DBOARD_HAS_PSRAM"
    ],

**Comment by brightproject** [comment]
> Why is your upload port different to the monitor port???

I flash via `USB`, and output the port monitor to a `USB-TTL` adapter on a `RX/TX` ESP32.

**Comment by sivar2311** [comment]
Wait... you're using a simulated ESP32-S3 on wokwi, not a physical ESP32-S3?
But you set serial port settings in platformio.ini
and remove things from the board.json file???

Then there is still the thing with the display....
I asked you to use a very basic project (see above).

In order to be able to help you, we have to build on the smallest common ground. 
This is an ESP32-S3-Devkit-C1 N16R8 - no more and no less!

**Comment by sivar2311** [comment]
Are you still there?

**Comment by sivar2311** [comment]
@brightproject Are you still there?

**Comment by brightproject** [comment]
> Wait... you're using a simulated ESP32-S3 on wokwi, not a physical ESP32-S3? But you set serial port settings in platformio.ini and remove things from the board.json file???
> 
> Then there is still the thing with the display.... I asked you to use a very basic project (see above).
> 
> In order to be able to help you, we have to build on the smallest common ground. This is an ESP32-S3-Devkit-C1 N16R8 - no more and no less!

I have a physical board.
![esp32_s3_display_spi](https://github.com/user-attachments/assets/f2cbc508-d1aa-4bbb-b702-2b691b41b25e)

I've tried a few experiments now.

> [env:esp32-s3-devkitc1-n16r8]
> ; platform = espressif32 @ 5.3.0 
> platform = espressif32 @ 6.6.0 
> board = esp32-s3-devkitc1-n16r8 
> framework = arduino 
> monitor_speed = 115200 
> monitor_port = COM6 
> upload_speed = 921600 
> upload_port = COM22 
> monitor_filters = esp32_exception_decoder 
> 
> lib_deps = bodmer/TFT_e SPI@^2.5.43 

If version `5.3.0` 
`Processing esp32-s3-devkitc1-n16r8 (platform: espressif32 @ 5.3.0; board: esp32-s3-devkitc1-n16r8; framework: arduino)` 
then the output [example](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/480%20x%20320/UTFT_Demo_480x320/UTFT_Demo_480x320.ino) with a display connected via `SPI` is `1363 msec`.
And if you update to version `6.6.0`
`Processing esp32-s3-devkitc1-n16r8 (platform: espressif32 @ 6.6.0; board: esp32-s3-devkitc1-n16r8; framework: arduino)`
then the output will be `842 msec`.

**Comment by sivar2311** [comment]
Sorry, I don't understand how I can help you.

Firstly it was about an `esp_core_dump_flash` error - which seems to be fixed now.

Now it is about the speed and version conflicts of the TFT_eSPI library.

This is no longer related to the files offered here.
For TFT_eSPI related questions, please open an issue at [bodmer/TFT_eSPI](https://github.com/Bodmer/TFT_eSPI/issues)

**Comment by brightproject** [comment]
> Sorry, I don't understand how I can help you.
> 
> Firstly it was about an `esp_core_dump_flash` error - which seems to be fixed now.
> 
> Now it is about the speed and version conflicts of the TFT_eSPI library.
> 
> This is no longer related to the files offered here. For TFT_eSPI related questions, please open an issue at [bodmer/TFT_eSPI](https://github.com/Bodmer/TFT_eSPI/issues)

Don't be offended, the information here is more for other developers, if someone has problems.
Yes, you helped me resolve the issues regarding `esp32-s3-n16-r8`.
Thank you and have a good evening.

**Comment by sivar2311** [comment]
@brightproject I don't understand your intentions. Even the various cross-links you generate make no sense.

**Comment by sivar2311** [comment]
@brightproject Maybe you should use the official `esp32-s3-devkitc-1.json` and just modify what's needed to make the N16R8 work.

See the settings for the `N16R8` in my other repo [ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations](https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations?tab=readme-ov-file#esp32-s3-wroom-11u-n16r16v)

**Comment by brightproject** [comment]
> @brightproject Maybe you should use the official `esp32-s3-devkitc-1.json` and just modify what's needed to make the N16R8 work.
> 
> See the settings for the `N16R8` in my other repo [ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations](https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations?tab=readme-ov-file#esp32-s3-wroom-11u-n16r16v)

Thanks for the links.
